### ISSUE TITLE
http://ka/full_map.jpg

### ISSUE THREAD

**Issue by skynet95** [interactive-game-maps/interactive-game-maps.github.io#1]
Game name:

High quality map images for layers:

* https://my-hq-map.image
* https://my-hq-map-2.image
* …

Create marker overlays for:

* Treasure Chests
* Oysters
* …

**Comment by interactive-game-maps** [comment]
I see there might have been some confusion this being an automated task.

I created a template repository and updated the readme.
Please have a look into the template repository to get started: https://github.com/interactive-game-maps/template#readme
